name: voice_assistant_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  google_mlkit_face_detection: ^0.13.1
  speech_to_text: ^7.0.0
  permission_handler: ^11.0.1
  flutter_tts: ^3.8.3
  cupertino_icons: ^1.0.8
  google_mlkit_commons: ^0.11.0
  animated_text_kit: ^4.2.3
  dio: ^5.8.0+1
  flutter_svg: ^2.2.0
  uuid: ^4.5.1
  scrollable_positioned_list: ^0.3.8
  auto_size_text: ^3.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/data/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/data/navBg.jpg
    